#!/usr/bin/env python3
"""Generate browsable Sources and Nuggets sections for the MkDocs site.

Mirrors sources/**/*.md into wiki/sources/ (metadata table + content) and
renders the nugget inventory as wiki/nuggets/index.md. Output directories are
generated at build time and gitignored — run this before `mkdocs build` /
`mkdocs serve`. The originals in sources/ and nuggets/ remain canonical.
"""
from __future__ import annotations

import shutil
from pathlib import Path

import yaml

import lint

ROOT = lint.ROOT
SOURCES = ROOT / "sources"
OUT_SOURCES = lint.WIKI / "sources"
OUT_NUGGETS = lint.WIKI / "nuggets"

META_ORDER = ("title", "author", "show", "episode", "published", "url",
              "origin", "audio_url", "retrieved", "type", "guid", "feed", "tags")


def meta_table(meta: dict) -> list[str]:
    lines = ["| Field | Value |", "|---|---|"]
    for key in META_ORDER:
        val = meta.get(key)
        if val in (None, "", []):
            continue
        if key in ("url", "audio_url") and str(val).startswith("http"):
            val = f"<{val}>"
        elif isinstance(val, list):
            val = ", ".join(str(v) for v in val)
        lines.append(f"| {key} | {val} |")
    return lines


def page_title(meta: dict, path: Path) -> str:
    return str(meta.get("title") or path.stem)


def generate_sources() -> list[tuple[str, Path, dict]]:
    """Mirror each source file into wiki/sources/. Returns (rel, out, meta)."""
    entries = []
    for src in sorted(SOURCES.rglob("*.md")):
        if src.name == "README.md":
            continue
        rel = src.relative_to(SOURCES)
        text = src.read_text(encoding="utf-8")
        meta, err = lint.parse_frontmatter(text)
        meta = meta or {}
        body = text
        if not err and text.startswith("---\n"):
            end = text.find("\n---", 4)
            body = text[end + 4:].lstrip("\n")
        title = page_title(meta, src)
        out = OUT_SOURCES / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            "---\n" + yaml.safe_dump({"title": title}, allow_unicode=True) + "---\n\n"
            + f"# {title}\n\n"
            + f"*Read-only mirror of `sources/{rel.as_posix()}` — the file in Git is canonical.*\n\n"
            + "\n".join(meta_table(meta)) + "\n\n---\n\n" + body,
            encoding="utf-8")
        entries.append((rel.as_posix(), out, meta))
    return entries


def sources_index(entries) -> None:
    lines = ["---", "title: Sources", "---", "", "# Sources",
             "", "*Generated by `scripts/build_browse.py` — raw material lives in `sources/` (append-only).*", ""]
    by_folder: dict[str, list] = {}
    for rel, out, meta in entries:
        by_folder.setdefault(rel.split("/")[0], []).append((rel, out, meta))
    for folder in sorted(by_folder):
        lines += [f"## {folder}/", "", "| Source | Type | Published | Retrieved |", "|---|---|---|---|"]
        for rel, out, meta in by_folder[folder]:
            link = out.relative_to(OUT_SOURCES).as_posix()
            lines.append(f"| [{page_title(meta, out)}]({link}) | {meta.get('type', '')} "
                         f"| {meta.get('published', '')} | {meta.get('retrieved', '')} |")
        lines.append("")
    (OUT_SOURCES / "index.md").write_text("\n".join(lines), encoding="utf-8")


def cell(text: str, limit: int = 110) -> str:
    """Make a string safe for a Markdown table cell."""
    text = " ".join(str(text).split()).replace("|", "\\|")
    return text[: limit - 1] + "…" if len(text) > limit else text


def render_nugget_page(path: Path, data: dict) -> int:
    source = str(data.get("source", ""))
    src_link = source.removeprefix("sources/")
    lines = ["---", f"title: Nuggets — {path.stem}", "---", "",
             f"# Nuggets — {path.stem}", "",
             f"Source: [{source}](../sources/{src_link}) · "
             "[all nuggets](index.md)", ""]
    count = 0
    for n in data.get("nuggets", []):
        if not isinstance(n, dict):
            continue
        count += 1
        badges = f"`{n.get('confidence', '?')}` · `{n.get('status', '?')}`"
        if n.get("tags"):
            badges += " · " + " ".join(f"`#{t}`" for t in n["tags"])
        lines += [f"### `{n.get('id', '?')}`", "",
                  f"> {str(n.get('claim', '')).strip()}", "",
                  f"**Context:** {str(n.get('context', '')).strip()}", ""]
        if n.get("quote"):
            lines += [f"**Quote:** “{str(n['quote']).strip()}”", ""]
        if n.get("superseded_by"):
            lines += [f"**Superseded by:** `{n['superseded_by']}`", ""]
        lines += [badges, ""]
    (OUT_NUGGETS / f"{path.stem}.md").write_text("\n".join(lines), encoding="utf-8")
    return count


def nuggets_pages() -> int:
    """One page per nugget file + a searchable flat index table."""
    rows = []
    count = 0
    files = 0
    for path in lint.nugget_files():
        data, err = lint.load_nuggets(path)
        if err or not data:
            continue
        files += 1
        count += render_nugget_page(path, data)
        for n in data.get("nuggets", []):
            if not isinstance(n, dict):
                continue
            nid = str(n.get("id", "?"))
            tags = " ".join(f"#{t}" for t in (n.get("tags") or []))
            rows.append(f"| [`{nid}`]({path.stem}.md#{nid}) | {cell(n.get('claim', ''))} "
                        f"| {n.get('confidence', '?')} | {n.get('status', '?')} "
                        f"| {cell(tags, 60)} |")
    lines = ["---", "title: Nugget inventory", "---", "", "# Nugget inventory", "",
             "*Generated by `scripts/build_browse.py` from `nuggets/` — claims are "
             "immutable; corrections supersede (see `policies/nugget-policy.md`).*", "",
             f"**{count} nuggets** from **{files} sources**. Every nugget below links "
             "to its full entry (claim, context, quote, source). Use the site search "
             "for full-text lookup across claims and contexts — results deep-link to "
             "individual nuggets.", "",
             "| Nugget | Claim | Confidence | Status | Tags |", "|---|---|---|---|---|"]
    lines += rows + [""]
    (OUT_NUGGETS / "index.md").write_text("\n".join(lines), encoding="utf-8")
    return count


def main():
    for out in (OUT_SOURCES, OUT_NUGGETS):
        shutil.rmtree(out, ignore_errors=True)
        out.mkdir(parents=True)
    entries = generate_sources()
    sources_index(entries)
    n = nuggets_pages()
    print(f"generated {len(entries)} source pages + nugget browser ({n} nuggets) "
          f"under wiki/sources/ and wiki/nuggets/")


if __name__ == "__main__":
    main()
